# Generated by Django 5.0.7 on 2024-07-20 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_reaction_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='comments',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.comments', verbose_name='Comentário'),
        ),
    ]
